name: apos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  loader_overlay: ^4.0.1
  loading_animation_widget: ^1.2.1
  package_info_plus: ^8.0.1
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  firebase_auth: ^5.1.4
  pin_code_fields: ^8.0.1
  curved_labeled_navigation_bar: ^2.0.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
